# Generated by Django 3.1.6 on 2021-02-12 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disc', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sala', models.CharField(max_length=80)),
                ('conteudo_sala', models.CharField(max_length=255)),
                ('codigo_sala', models.CharField(max_length=10)),
                ('desc_sala', models.TextField()),
                ('jogo_sala', models.IntegerField(default=0)),
                ('visibilidade_sala', models.BooleanField(default=True)),
                ('adm_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ManyToManyField(to='core.Disciplina')),
            ],
            options={
                'db_table': 'sala',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eixoEconomico_resultado', models.IntegerField()),
                ('eixoSocial_resultado', models.IntegerField()),
                ('eixoDiplomatico_resultado', models.IntegerField()),
                ('eixoCivil_resultado', models.IntegerField()),
                ('data_resultado', models.DateTimeField(auto_now=True)),
                ('usuario_resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'resultados',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_mensagem', models.DateTimeField(auto_now=True)),
                ('texto_mensagem', models.TextField()),
                ('sala_mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
                ('usuario_mensagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mensagem',
            },
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_conquista', models.CharField(max_length=80)),
                ('desc_conquista', models.TextField()),
                ('usuario_conquista', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conquista',
            },
        ),
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sala')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alunos',
            },
        ),
    ]
