# Generated by Django 3.1.6 on 2021-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultado',
            name='eixoCivil_resultado',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='eixoDiplomatico_resultado',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='eixoEconomico_resultado',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='resultado',
            name='eixoSocial_resultado',
            field=models.FloatField(),
        ),
    ]
